-- ============================================================
-- ABUSHA - COMPLETE SUPABASE SETUP
-- Run this ENTIRE file once in Supabase SQL Editor.
-- It creates the database, storage buckets, RLS policies and RPCs.
-- ============================================================

create extension if not exists pgcrypto;

create table if not exists public.client_docs (
  id bigint generated by default as identity primary key,
  otp text not null unique,
  name text not null,
  age integer,
  gender text,
  email text,
  phone text,
  dob date,
  place text,
  country text,
  passport text,
  photo_url text,
  title text,
  content text,
  receipt_url text,
  payment_status text not null default 'pending'
    check (payment_status in ('pending','approved','rejected')),
  payment_submitted_at timestamptz,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Only explicitly approved Supabase Auth users are admins.
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.client_docs enable row level security;
alter table public.admin_users enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- Client records: public can only create registrations.
drop policy if exists "Public can register clients" on public.client_docs;
create policy "Public can register clients"
on public.client_docs for insert to anon, authenticated
with check (true);

-- Only admin users can read/change/delete client records.
drop policy if exists "Authenticated admins can read clients" on public.client_docs;
drop policy if exists "Authenticated admins can update clients" on public.client_docs;
drop policy if exists "Authenticated admins can delete clients" on public.client_docs;
create policy "Authenticated admins can read clients"
on public.client_docs for select to authenticated
using (public.is_admin());
create policy "Authenticated admins can update clients"
on public.client_docs for update to authenticated
using (public.is_admin()) with check (public.is_admin());
create policy "Authenticated admins can delete clients"
on public.client_docs for delete to authenticated
using (public.is_admin());

-- Storage buckets. These are created HERE, not inside your website folder.
insert into storage.buckets (id, name, public)
values ('client-photos', 'client-photos', true)
on conflict (id) do update set public = true;

insert into storage.buckets (id, name, public)
values ('payment-receipts', 'payment-receipts', false)
on conflict (id) do update set public = false;

-- Anyone may upload a registration photo or payment receipt.
drop policy if exists "Public can upload client photos" on storage.objects;
drop policy if exists "Public can upload payment receipts" on storage.objects;
create policy "Public can upload client photos"
on storage.objects for insert to anon, authenticated
with check (bucket_id = 'client-photos');
create policy "Public can upload payment receipts"
on storage.objects for insert to anon, authenticated
with check (bucket_id = 'payment-receipts');

-- Only admins can manage/read/delete stored files.
drop policy if exists "Authenticated admins can manage storage" on storage.objects;
create policy "Authenticated admins can manage storage"
on storage.objects for all to authenticated
using (bucket_id in ('client-photos','payment-receipts') and public.is_admin())
with check (bucket_id in ('client-photos','payment-receipts') and public.is_admin());

-- Generate a unique 6-digit OTP.
create or replace function public.generate_client_otp()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_otp text;
begin
  loop
    v_otp := lpad((floor(random() * 900000) + 100000)::int::text, 6, '0');
    exit when not exists (select 1 from public.client_docs where otp = v_otp);
  end loop;
  return v_otp;
end;
$$;

-- Public OTP lookup. It intentionally exposes the document associated with an OTP.
create or replace function public.get_client_by_otp(p_otp text)
returns setof public.client_docs
language sql
security definer
set search_path = public
as $$
  select * from public.client_docs
  where otp = trim(p_otp)
  limit 1;
$$;

-- Public payment-receipt submission.
create or replace function public.submit_payment_receipt(
  p_otp text,
  p_receipt_url text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.client_docs
  set receipt_url = p_receipt_url,
      payment_status = 'pending',
      payment_submitted_at = now(),
      updated_at = now()
  where otp = trim(p_otp);
  return found;
end;
$$;

revoke all on function public.generate_client_otp() from public;
grant execute on function public.generate_client_otp() to anon, authenticated;
revoke all on function public.get_client_by_otp(text) from public;
grant execute on function public.get_client_by_otp(text) to anon, authenticated;
revoke all on function public.submit_payment_receipt(text,text) from public;
grant execute on function public.submit_payment_receipt(text,text) to anon, authenticated;

grant usage, select on sequence public.client_docs_id_seq to anon, authenticated;
grant insert on public.client_docs to anon, authenticated;
grant select, update, delete on public.client_docs to authenticated;

-- IMPORTANT: after creating your admin in Supabase Authentication -> Users,
-- run this once with that user's UUID:
-- insert into public.admin_users (user_id) values ('PASTE-AUTH-USER-UUID-HERE');
